[server]
# Enable CORS for reverse proxy
enableCORS = false
enableXsrfProtection = false

# WebSocket compression can cause issues with some reverse proxies
enableWebsocketCompression = false

# The base URL path will be set dynamically via the entrypoint script
# This file provides default configuration; baseUrlPath is set via CLI
